### PR TITLE
Feature/login

### PR DESCRIPTION
**Pull request by lschimm**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Ran on local environment, logged in, and redirected to profile page
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Comment by hunterraffety** [comment]
That's not an issue with the code. There is an issue with your endpoint or database on your end that is causing that issue.

**Comment by ticotheps** [comment]
> That's not an issue with the code. There is an issue with your API/endpoint or database on your end that is causing that issue.
> 
> Mikis is reviewing the PR for the merge conflicts right now.

**Comment by ticotheps** [comment]
You are right! I was being a dumb dumb and forgot to do a 'git pull origin development' before checking out your branch! It renders perfectly now! Still merge conflicts though?

**Comment by hunterraffety** [comment]
Working on it 8)

**Comment by ticotheps** [comment]
Sorry, I accidentally closed the pull request when I MEANT to close my comment. My BAD!

**Comment by ticotheps** [comment]
Hunter and Leilani, am I looking for the server error display or is this PR just for the AWESOME styles? :)

**Comment by hunterraffety** [comment]
Make it error.

image

**Comment by ticotheps** [comment]
Worked like a charm! 
Screen Shot 2019-08-29 at 5 49 09 PM

**Pull request merged**
